### ISSUE TITLE
Correct Xbee wake procedure

### ISSUE THREAD

**Issue by cujomalainey** [cujomalainey/Mass-Tach-Sensors#10]
Currently it is waiting for arbitrary packets and then sending the messaged, this needs to be changed to make sure it is modem status packets and that things are send properly

**Comment by Loonman** [comment]
xBee is currently finding modem status packets, need to make sure that it finds a disassociated/reset and then a reassociated packet in the correct order.

**Comment by cujomalainey** [comment]
moved to jira
